---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    # Group all patch updates into a single PR
    groups:
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
    commit-message:
      include: "scope"
      prefix: "build"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    # Group all patch updates into a single PR
    groups:
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
    commit-message:
      include: "scope"
      prefix: "build"
